### ISSUE TITLE
Some pages are not working in the wiki

### ISSUE THREAD

**Issue by adnaneGdihi** [vnegnev/marcos_extras#16]
The pages for setting up marcos redirects to wiki home page

**Comment by vnegnev** [comment]
That's strange, it works for me - do you mean this link?
![image](https://github.com/vnegnev/marcos_extras/assets/4116364/b8a777ea-46e1-4a10-b614-4c621a0f7063)

The direct link is https://github.com/vnegnev/marcos_extras/wiki/guide_setting_marcos_up . Some of the information there is a bit old and I haven't tried running through the steps in over a year, so please post here if you hit any problems.

**Comment by adnaneGdihi** [comment]
yes, that link it is odd and redirects to the wiki home page. I encountered the same issue on most of the link listed under **Quick links**.

**Comment by vnegnev** [comment]
I see, the links were partly broken further down on the page (not the link I circled though). Could you please try it now?

**Comment by vnegnev** [comment]
Closing as I think it's fixed now.
