### ISSUE TITLE
No blue light after copy_bitstream.sh is run

### ISSUE THREAD

**Issue by vnegnev** [vnegnev/marcos_extras#17]
Issue based on https://github.com/vnegnev/marcos_extras/discussions/9#discussioncomment-9012741 which might indicate one of the following:

- Mismatch in SSH versions
- Silent failure due to an error on the SDRLab which isn't being shown in the terminal

@josalggui could you please try running the commands in copy_bitstream.sh manually, and see if that also fails? Please post any error messages here.

**Comment by josalggui** [comment]
It works to me using the commit 433936cf245b5645ead3feb6891acf48bf9c2d18 from Jun 4th 2022. Once I did the marcos_setup.sh from this commit the blue light turns on. And now, going back to last commit works also. It looks like if the first time after installing Yocto I have to go to an older version of marcos_extras. Does this tell you something?

**Comment by josalggui** [comment]
In 433936cf245b5645ead3feb6891acf48bf9c2d18, marcos_setup.sh successfully copies ocra_mri_rp-122.bit.bin and .dtbo files. However, in the latest commit, it fails to copy marcos_fpga_rp-122.bit.bin and .dtbo files.

I will try this monday step by step.

**Comment by josalggui** [comment]
After conducting aditional tests, it appears that marcos_setup.sh successfully copies the marcos_fpga files. However, it seems that the blue LED only activates when the ocra_mri files are located in the lib/firmware directory within the SD card.

**Comment by vnegnev** [comment]
Sorry about the delay - something went wrong with notifications. This looks like the SCP command isn't working due to some kind of version mismatch. It's been deprecated for a few years already, so I will try and update the script to more intelligently copy the files from the host to the SDRLab. Thanks for the detailed debugging!

**Comment by vnegnev** [comment]
To be clearer, it probably worked on my machine because it's using a newer version of OpenSSH where the `scp -O` flag correctly works, so everything ran fine on mine. I'll try and debug it with an old version of Ubuntu - are you using Ubuntu 22.04?

**Comment by josalggui** [comment]
I did the test under ubutnu 22.04, also under windows 10 22H2 with identical results.

**Comment by vnegnev** [comment]
I think I've found the underlying problem - it dates back to when MaRCoS moved away from the ocra build in 2020, and it turns out that the DTBO devicetree file (which specifies details about the FPGA bitstream to the Linux kernel) was still referring to an old bitstream. This is corrected in the latest master commit; please let me know if it's fixed the problem for you.

**Comment by jmalgarin86** [comment]
Tested and working! Thanks!

**Comment by josalggui** [comment]
Tested and working! Thanks!
